FROM python:3.10-slim

RUN pip install --no-cache-dir mlflow==2.17.2

EXPOSE 5000

CMD ["mlflow", "server", \
     "--backend-store-uri", "sqlite:////mlflow/db/mlflow.db", \
     "--artifacts-destination", "/mlflow/artifacts", \
     "--host", "0.0.0.0", \
     "--port", "5000"]
